version: '3.8'

services:
  app:
    build: '.'
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - TF_CPP_MIN_LOG_LEVEL=3
      - GRAPH_DEFINITIONS_LOCATION=/workflows/
      - MODEL_DEFINITIONS_LOCATION=/models/

    volumes:
      - /tmp/models/:/models/
      - /tmp/workflows/:/workflows

  nginx:
    build: './nginx'
    ports:
      - '80:1337'
    depends_on:
      - app